<div class="page-header">
	<h1>Submission</h1>
</div>

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {		
						
						jQuery.validator.addMethod("source", function(value, element) {
							return value || $("#source").val();
						}, "Select a file");
						
						$("#jq-validation-form").validate({
							ignore: '.ignore, .select2-input',
							focusInvalid: false,
							rules: {
								'problem': {
								  required: true,
								  digits: true
								},
								'file': {
								  source: true,
								}
							},
							errorPlacement: function(error, element) {
								error.addClass("help-block");
								if (element.attr("type") == "file") error.insertAfter(element.parent());
								else error.insertAfter(element);
							}
						});
					});
				</script>

		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">Quick Submit</span>
			</div>
			<div class="panel-body">

				<?php if($this->error) echo "<div class='note note-danger'>$this->error</div>"; ?>			
				<?php if($this->success) { ?>			

					<div id="success" class="modal modal-alert modal-success fade">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<i class="fa fa-check-circle"></i>
							</div>
							<div class="modal-title"><?php echo $this->success;?></div>
							<div class="modal-footer">
								<button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
							</div>
						</div>
					</div>
				</div>
				<script>
						init.push(function(){ 
							$('#success').on('hide.bs.modal',function(e){ document.location = "index.php/submission/user"; });
							$('#success').modal();
						});
					</script>
				<?php } ?>
				
				<form class="form-horizontal" id="jq-validation-form" method="post" enctype="multipart/form-data">
					<div class="form-group">
						<label for="problem" class="col-sm-3 control-label">Problem</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="problem" name="problem" placeholder="Problem" value="<?php echo $_POST["problem"]; ?>">
						</div>
					</div>

					<div class="form-group">
						<label for="language" class="col-sm-3 control-label">Language</label>
						<div class="col-sm-7">
							<select name="language" id="language" class="form-control">
								<option value="2" <?php if($_POST['language'] == 2) echo "selected='selected'";?>>C++</option>
								<option value="1" <?php if($_POST['language'] == 1) echo "selected='selected'";?>>C</option>
							</select>
						</div>
					</div>

					<div class="form-group">
						<label for="file" class="col-sm-3 control-label">Source File</label>
						<script>
							init.push(function () {
								$('#file').pixelFileInput({ placeholder: 'No file selected...' });
							})
						</script>
						<div class="col-sm-7">
							<input type="file" id="file" name="file">
						</div>
					</div>

					<div class="form-group">
						<label for="file" class="col-sm-3 control-label">Source Code</label>
						<script>
							init.push(function () {
								$("#jq-expanding-source").expandingInput({
									target: 'textarea',
									placeholder: '',
									onBeforeExpand: function () { },
									onAfterExpand: function () { this.$target.attr('rows', 20); }
								});
							})
						</script>
						<div class="col-sm-7">
							<div id="jq-expanding-source">
								<textarea rows="1" class="form-control" name="source" id="source"><?php echo $_POST["source"]; ?></textarea>
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<button type="submit" class="btn btn-primary">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>