<div class="page-header">
	<h1>Submissions</h1>
</div>

<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">All Submissions</span>
			</div>
			<div class="panel-body">
				<div class="table-primary">
					<table cellpadding="0" cellspacing="0" border="0"
						class="table table-striped table-bordered"
						id="datatables-problems">
						<thead>
							<tr>
								<th style="width: 100px; min-width: 100px;">Id</th>
								<th style="width: 100px; min-width: 100px;">Problem</th>
								<th>User</th>
								<th style="width: 100px; min-width: 100px;">Time</th>
								<th style="width: 100px; min-width: 100px;">Date</th>
								<th style="width: 100px; min-width: 100px;">Language</th>
							</tr>
						</thead>
						<tbody>
							<!-- 		<?php #for($i=0; $i<100; $i++){ ?>
							<tr class="odd gradeX" onclick="document.location='index.php/p/<?php echo $problem['id']; ?>'">
								<td><?php# echo $i+1; ?></td>
								<td>Name</td>
								<td>0.002</td>
								<td>C++</td>
							</tr>
			-->			<?php #}?>
						<?php $i=1; foreach($this->submissions as $subs){ ?>
							<tr class="odd gradeX"
								onclick="document.location='index.php/u/<?php echo $subs['user']; ?>'">
								<td><?php echo $subs['submission.id']; ?></td>
								<td><?php echo $subs['problem']; ?></td>
								<td><?php echo $subs['name']; ?></td>
								<td><?php echo $subs['time']; ?></td>
								<td><?php echo $subs['date']; ?></td>
								<td><?php echo $subs['langueage']==1? "C" :"C++"; ?></td>
							</tr>
						<?php }?>
						
						
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>