<div class="page-header">
	<h1>Ranking</h1>
</div>

			
			<script>
				init.push(function () {
					$('#datatables').dataTable();
					$('#datatables_wrapper .table-caption').text('<?php echo $this->title;?>');
					$('#datatables_wrapper .dataTables_filter input').attr('placeholder', 'Search...');
				});
			</script>
			
			<div class="panel-body">
				<div class="table-primary">
					<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="datatables">
						<thead>
							<tr>
								<th style="width: 80px; min-width: 80px;">Number</th>
								<th style="width: 80px; min-width: 80px;">Id</th>
								<th>User</th>
								<th style="width: 100px; min-width: 100px;">Problems Solved</th>
							</tr>
						</thead>
						<tbody>
							
						<?php $i=1; foreach($this->users as $user){ ?>
							<tr class="odd gradeX"
								>
								<td><?php echo $i; ?></td>
								<td><?php echo $user['user_id']; ?> </td>
								<td><a href="index.php/u/<?php echo $user['login']; ?>"><?php echo $user['name']; ?></a></td>
								<td><?php echo $user['con']; ?> </td> 
								
							</tr>
						<?php $i++;}?>
						
						
						</tbody>
					</table>
				</div>
			</div>
