<div class="page-header">
	<h1>Submissions</h1>
</div>

<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">My Submissions</span>
			</div>
			
			<script>
				init.push(function () {
					$('#datatables').dataTable();
					$('#datatables_wrapper .table-caption').text('<?php echo $this->title;?>');
					$('#datatables_wrapper .dataTables_filter input').attr('placeholder', 'Search...');
				});
			</script>
			
			<div class="panel-body">
				<div class="table-primary">
					<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="datatables">
						<thead>
							<tr>
								<th style="width: 80px; min-width: 80px;">Number</th>
								<th>Problem</th>
								<th style="width: 80px; min-width: 80px;">Time</th>
								<th style="width: 150px; min-width: 150px;">Date</th>
								<th style="width: 100px; min-width: 100px;">Language</th>
								<th style="width: 100px; min-width: 100px;">State</th>
							</tr>
						</thead>
						<tbody>
							
						<?php $i=1; foreach($this->submissionsUser as $subs){ ?>
							<tr class="odd gradeX"
								>
								<td><?php echo $subs['id']; ?></td>
								<td><a href="index.php/p/<?php echo $subs['problem']; ?>"><?php echo $subs['problem']." - ".$subs['title']; ?></a></td>
								<td><?php echo $subs['time']; ?> ms</td> 
								<td><?php echo $subs['date']; ?></td>
								<td><?php echo $subs['language']==1? "C" :"C++"; ?></td>
								<td>
									<?php 
									if($subs['state']==0 && $subs['date_judge']) echo '<span class="label label-info ticket-label">On Judgement</span>';
									else if($subs['state']==0) echo '<span class="label label-info ticket-label">In Queue</span>';
									else if($subs['state']==1) echo '<span class="label label-success ticket-label">Accepted</span>';
									else if($subs['state']==2) echo '<span class="label label-danger ticket-label">Presentation Error</span>';
									else if($subs['state']==3) echo '<span class="label label-danger ticket-label">Wrong Answer</span>';
									else if($subs['state']==4) echo '<span class="label label-danger ticket-label">Compilation Error</span>';
									else if($subs['state']==5) echo '<span class="label label-danger ticket-label">Runtime Error</span>';
									else if($subs['state']==6) echo '<span class="label label-danger ticket-label">Time Limit Exceded</span>';
									?>
								</td>
							</tr>
						<?php }?>
						
						
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>