<ul class="breadcrumb breadcrumb-page">
</ul>
<div class="page-header">

	<div class="row">
		<!-- Page header, center on small screens -->
		<h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
			<i class="fa fa-dashboard page-header-icon"></i>&nbsp;&nbsp;Home
		</h1>

		<div class="col-xs-12 col-sm-8">
			<div class="row">
				<hr class="visible-xs no-grid-gutter-h">
				<!-- "Create project" button, width=auto on desktops -->
				<div class="pull-right col-xs-12 col-sm-auto">
					<a href="#" class="btn btn-primary btn-labeled"
						style="width: 100%;"><span class="btn-label icon fa fa-plus"></span>Sugest
						new problem</a>
				</div>

				<!-- Margin -->
				<div class="visible-xs clearfix form-group-margin"></div>

				<!-- Search field -->
				<form action="" class="pull-right col-xs-12 col-sm-6">
					<div class="input-group no-margin">
						<span class="input-group-addon"
							style="border: none; background: #fff; background: rgba(0, 0, 0, .05);"><i
							class="fa fa-search"></i></span> <input type="text"
							placeholder="Search Problems..."
							class="form-control no-padding-hr"
							style="border: none; background: #fff; background: rgba(0, 0, 0, .05);">
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- / .page-header -->


<div class="row">
	<div class="col-md-8">
		<div class="panel colourable">
			<div class="panel-heading">
				<span class="panel-title">Bem Vindo ao UFFS Online Judge</span>
			</div>
			<div class="panel-body">
				<p>A Universidade Federal da Fronteira Sul (UFFS) é uma instituição
					de ensino superior pública e popular. Criada pela lei no 12.029, de
					15 de setembro de 2009, a UFFS abrange os 396 municípios da
					Mesorregião Fronteira Mercosul – Sudoeste do Paraná, Oeste de Santa
					Catarina e Noroeste do Rio Grande do Sul.</p>
				<p>Desde sua criação, a UFFS tem cinco campi – Chapecó (SC) – sede
					da instituição -, Realeza e Laranjeiras do Sul (PR) e Cerro Largo e
					Erechim (RS). Historicamente desassistida pelo poder público,
					especialmente com relação ao ensino superior, a mesorregião sonhava
					com uma universidade federal há décadas.</p>
				<p>Com 33 cursos em 42 turmas ingressantes anualmente, a
					universidade prevê ter 10 mil alunos nos primeiros cinco anos. As
					graduações oferecidas privilegiam as vocações da economia regional
					– visando o desenvolvimento regional integrado, pela valorização e
					superação da matriz produtiva - e estão em consonância com a
					Política Nacional de Formação de Professores do Ministério da
					Educação (MEC).</p>
			</div>
		</div>


		<div class="row">
			<script>
				init.push(function () {
					$('#novos-problemas .list-group').slimScroll({ height: 300, alwaysVisible: true, color: '#888',allowPageScroll: true });
				})
			</script>
			<style>
#novos-problemas li {
	display: table;
	width: 100%;
}
</style>

			<div class="col-md-6">
				<div class="panel panel-warning" id="novos-problemas">
					<div class="panel-heading">
						<span class="panel-title"><i
							class="panel-title-icon fa fa-bullhorn"></i>News Problems</span>
					</div>
					<div class="padding-sm-vr">
						<ul class="list-group">
							<?php foreach($this->problems as $problem){ ?>
							<li class="list-group-item padding-sm no-border-hr no-border-t">
								<div class="pull-left">
									<a href="index.php/p/<?php echo $problem['id']; ?>" title=""><?php echo $problem['title']; ?></a>
									<div class="text-slim">por <?php echo $problem['from']; ?></div>
								</div>
								<div class="pull-right text-slim text-sm"><?php echo $problem['date']; ?></div>
							</li>
							<?php }?>
						</ul>
					</div>
				</div>
			</div>

			<script>
				init.push(function () {
					$('#novos-usuarios .list-group').slimScroll({ height: 300, alwaysVisible: true, color: '#888',allowPageScroll: true });
				})
			</script>
			<style>
#novos-usuarios li {
	display: table;
	width: 100%;
}
</style>

			<div class="col-md-6">
				<div class="panel panel-warning" id="novos-usuarios">
					<div class="panel-heading">
						<span class="panel-title"><i
							class="panel-title-icon fa fa-bullhorn"></i>New Users</span>
					</div>
					<div class="padding-sm-vr">
						<ul class="list-group">
							<?php foreach($this->users as $user){ ?>
							<li class="list-group-item padding-sm no-border-hr no-border-t">
								<img
								src="http://www.gravatar.com/avatar/<?php echo md5($user['email'])?>?d=mm&s=280"
								alt="" class="pull-left avatar-sm" />
								<div class="pull-left">
									<a href="index.php/u/<?php echo $user['login']; ?>" title=""><?php echo $user['name']; ?></a>
									<div class="text-slim"><?php echo $user['instituition'];?></div>
								</div>
								<div class="pull-right text-slim text-sm valign-bottom"><?php echo $user['date'];?></div>
							</li>
							<?php }?>	
						</ul>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-success widget-support-tickets">
					<div class="panel-heading">
						<span class="panel-title"><i
							class="panel-title-icon fa fa-bullhorn"></i>Recent submissions</span>
					</div>
					<!-- / .panel-heading -->
					<div class="panel-body tab-content-padding">
						<!-- Panel padding, without vertical padding -->
						<div class="panel-padding no-padding-vr">
							<?php foreach($this->submissions as $subs){ ?>
								<div class="ticket">
									<?php
								
								if ($subs ['state'] == 0) {
									$state = 'In Queue';
									?>										
											<span class="btn btn-success btn-xs btn-outline ticket-label"><?php echo $state?></span>
									<?php };?>
									<?php
								
								if ($subs ['state'] == 1) {
									$state = 'Accepted';
									?>										
											<span class="label label-success ticket-label"><?php echo $state?></span>
									<?php };?>
									<?php
								
								if ($subs ['state'] == 2) {
									$state = 'Presentation Error';
									?>										
											<span class="label ticket-label"><?php echo $state?></span>
									<?php };?>
									<?php
								
								if ($subs ['state'] == 3) {
									$state = 'Wrong Wasner';
									?>										
											<span class="label label-danger ticket-label"><?php echo $state?></span>
									<?php };?>
									<?php
								
								if ($subs ['state'] == 4) {
									$state = 'Compilation Error';
									?>										
											<span class="label label-warning ticket-label"><?php echo $state?></span>
									<?php };?>
									<?php
								
								if ($subs ['state'] == 5) {
									$state = 'Runtime Error';
									?>										
											<span class="label label-warning ticket-label"><?php echo $state?></span>
									<?php };?>	
									<?php
								
								if ($subs ['state'] == 6) {
									$state = 'Time Limit exceeded';
									?>										
											<span class="label label-info ticket-label"><?php echo $state?></span>
									<?php };?>																						
									<a href="index.php/p/<?php echo $subs['problem']; ?>" title=""
									class="ticket-title"><?php echo $subs['title']?><span>[#<?php echo $subs['problem'];?>]</span></a>
								<span class="ticket-info">Submitted by <a
									href="index.php/u/<?php echo $subs['login']; ?>" title=""><?php echo $subs['name'];?>
									</a> <?php echo $subs['date'];?>
									</span>
							</div>
							<?php }?>
							<!-- / .ticket -->
						</div>
					</div>
					<!-- / .panel-body -->
				</div>
				<!-- / .panel -->
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="row">
			<div class="col-sm-4 col-md-12">


				<style>
#top10 .points {
	margin-top: 4px;
}
</style>

				<div class="stat-panel" id="top10">
					<div class="stat-cell bg-danger valign-middle">
						<i class="fa fa-trophy bg-icon"></i> <span class="text-xlg"><strong>TOP
								10</strong></span><br> <span class="text-bg">2014</span><br>
					</div>
					<div class="stat-row">
						<div
							class="stat-cell col-sm-4 padding-sm-hr bordered no-border-r valign-top">
							<ul class="list-group no-margin">
								<li
									class="list-group-item no-border padding-xs-hr no-bg no-border-radius">
									<img src="assets/demo/avatars/5.jpg" alt="" class="avatar-xm" />
									<span class="text-bg">1º</span> <span class="padding-xs-hr">Documents</span>
									<div class="pull-right points">
										<span class="label label-success">34</span>
									</div>
								</li>
								<li class="list-group-item no-border-hr padding-xs-hr no-bg"><img
									src="assets/demo/avatars/5.jpg" alt="" class="avatar-xm" /> <span
									class="text-bg">1º</span> <span class="padding-xs-hr">Documents</span>
									<div class="pull-right points">
										<span class="label label-success">34</span>
									</div></li>
								<li
									class="list-group-item no-border-hr padding-xs-hr padding-xs-vr no-bg">
									<img src="assets/demo/avatars/5.jpg" alt="" class="avatar-xm" />
									<span class="text-bg">1º</span> <span class="padding-xs-hr">Documents</span>
									<div class="pull-right points">
										<span class="label label-success">34</span>
									</div>
								</li>
								<li class="list-group-item no-border-hr padding-xs-hr no-bg"><span
									class="text-bg padding-xs-hr">4º</span> Documents <span
									class="label label-success pull-right">34</span></li>
								<li class="list-group-item no-border-hr padding-xs-hr no-bg"><span
									class="text-bg padding-xs-hr">5º</span> Documents <span
									class="label label-success pull-right">34</span></li>
								<li class="list-group-item no-border-hr padding-xs-hr no-bg"><span
									class="text-bg padding-xs-hr">6º</span> Documents <span
									class="label label-success pull-right">34</span></li>
								<li class="list-group-item no-border-hr padding-xs-hr no-bg"><span
									class="text-bg padding-xs-hr">7º</span>Documents <span
									class="label label-success pull-right">34</span></li>
								<li class="list-group-item no-border-hr padding-xs-hr no-bg"><span
									class="text-bg padding-xs-hr">8º</span> Documents <span
									class="label label-success pull-right">34</span></li>
								<li class="list-group-item no-border-hr padding-xs-hr no-bg"><span
									class="text-bg padding-xs-hr">9º</span> Documents <span
									class="label label-success pull-right">34</span></li>
								<li class="list-group-item no-border padding-xs-hr no-bg"><span
									class="text-bg padding-xs-hr">10º</span> Documents <span
									class="label label-success pull-right">34</span></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Page wide horizontal line -->
<hr class="no-grid-gutter-h grid-gutter-margin-b no-margin-t">

