<script>
	function removeTag(id) {
		bootbox.confirm({
			message: "Are you sure?",
			callback: function(result) {
				if(result) document.location = "index.php/tag/remove/id/"+id;
			},
			className: "bootbox-sm"
		});
	};
</script>

<div class="page-header">
	<h1>Tags</h1>
	<div class="btn-group btn-group pull-right">
		<a class="btn btn-primary" href="index.php/tag/register">New Tag</a>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {
						$('#datatables-tags').dataTable();
						$('#datatables-tags_wrapper .table-caption').text('List All Tags');
						$('#datatables-tags_wrapper .dataTables_filter input').attr('placeholder', 'Search...');
					});
				</script>

		<div class="panel">
			<div class="panel-body">
				<div class="table-primary">
					<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="datatables-tags">
						<thead>
							<tr>
								<th>Name</th>
								<th style="width: 130px; min-width: 130px">Action</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach($this->tags as $tag){ ?>
							<tr class="odd gradeX">
								<td><?php echo $tag['name']; ?></td>
								<td>
									<div class="btn-group btn-group pull-right">
										<a class="btn btn-primary btn-outline btn-sm" href="index.php/tag/edit/id/<?php echo $tag['id'];?>">Change</a>
										<button class="btn btn-primary btn-outline btn-sm" id="remove" onclick="removeTag(<?php echo $tag['id'];?>)">Remove</button>
									</div>
								</td>
							</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>


