<div class="page-header">
	<h1>User</h1>
</div>

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {		
						
						jQuery.validator.addMethod("alphanumeric", function(value, element) {
							return this.optional(element) || /^\w+$/i.test(value);
						}, "Letters, numbers, and underscores only please");
						
						$("#jq-validation-form").validate({
							ignore: '.ignore, .select2-input',
							focusInvalid: false,
							rules: {
								'name': {
								  required: true,
								}	
							},
							messages: {
								'jq-validation-policy': 'You must check it!'
							}
						});
					});
				</script>

		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">Sign Up</span>
			</div>
			<div class="panel-body">

				<?php if($this->error) echo "<div class='note note-danger'>$this->error</div>"; ?>			
				<?php if($this->success) { ?>			

					<div id="success" class="modal modal-alert modal-success fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<i class="fa fa-check-circle"></i>
								</div>
								<div class="modal-title"><?php echo $this->success;?></div>
								<div class="modal-footer">
									<button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
								</div>
							</div> 
						</div> 
					</div>
					<script>
						init.push(function(){ 
							$('#success').on('hide.bs.modal',function(e){ document.location = "index.php/user/"; });
							$('#success').modal();
						});
					</script>
				<?php } ?>
				
				<form class="form-horizontal" id="jq-validation-form" method="post">
					<div class="form-group">
						<label for="name" class="col-sm-3 control-label">Name</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="name" name="name"
								placeholder="Name" value="<?php echo $_POST["name"]; ?>">
						</div>
					</div>			
				
					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<button type="submit" class="btn btn-primary">Confirm</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- /5. $JQUERY_VALIDATION -->