<div class="page-header">
	<h1>Constest</h1>
</div>

<div class="row">

	<div class="panel">
		<div class="panel-heading">
			<span class="panel-title">Informations</span>
		</div>
		<div class="panel-body">
			<div class="col-sm-12">

				<ul class="nav nav-tabs bs-tabdrop-example" show>
					<li class=""><a href="#bs-tabdrop-tab1" data-toggle="tab">Participants</a></li>
					<li class=""><a href="#bs-tabdrop-tab2" data-toggle="tab">Problems</a></li>
				</ul>
				<div class="tab-content tab-content-bordered">
					<div class="tab-pane" id="bs-tabdrop-tab1">
						<div class="table-primary">
							<table cellpadding="0" cellspacing="0" border="0"
								class="table table-striped table-bordered"
								id="datatables-problems">
								<thead>
									<tr>
										<th style="width: 80px; min-width: 250px;">User</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">A</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">B</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">C</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">D</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">E</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">F</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">G</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">H</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">I</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">J</th>
										<th style="width: 60px; min-width: 60px; text-align: center;">Punctuation</th>
									</tr>
								</thead>
								<tbody>
									<?php foreach($this->contestrank as $user){ ?>
									<tr>
										<td><a href="index.php/user/index/id/<?php echo $user['name']; ?>"><?php echo $contestuser['name']; ?></a></td>
										<td class="text-center"><a href="#">-</a></td>
										<td class="text-center"><a href="#">-</a></td>
										<td class="text-center"><a href="#">-</a></td>
										<td class="text-center"><a href="#">-</a></td>
										<td class="text-center"><a href="#">-</a></td>
										<td class="text-center"><a href="#">-</a></td>
										<td class="text-center"><a href="#">-</a></td>
										<td class="text-center"><a href="#">-</a></td>
										<td class="text-center"><a href="#">-</a></td>
										<td class="text-center"><a href="#">-</a></td>
										<td class="text-center"><a href="#">Score</a></td>
									</tr>
									<?php }?>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane" id="bs-tabdrop-tab2">
						<div class="table-primary">
							<table cellpadding="0" cellspacing="0" border="0"
								class="table table-striped table-bordered"
								id="datatables-problems">
								<thead>
									<tr>
										<th style="width: 60px; min-width: 60px;">Number</th>
										<th>Title</th>
									</tr>
								</thead>
								<tbody>
								<?php foreach($this->contests as $contest){ ?>
									<tr class="odd gradeX">
										<td><?php echo $contest['id']; ?></td>
										<td><a href="index.php/problem/index/id/<?php echo $contest['id']; ?>"><?php echo $contest['title']; ?></a></td>
									</tr>
								<?php }?>
								</tbody>
							</table>
						</div>
					</div>
				</div>

			</div>
		</div>

	</div>
</div>