<div class="page-header">
	<h1>Constest</h1>
</div>

<div class="row">

	<div class="panel">
		<div class="panel-heading">
			<span class="panel-title">Informations</span>
		</div>
		<div class="panel-body">
			<div class="col-sm-12">

				<ul class="nav nav-tabs bs-tabdrop-example">
					<li class=""><a href="#bs-tabdrop-tab1" data-toggle="tab">Section 1</a></li>
					<li class=""><a href="#bs-tabdrop-tab2" data-toggle="tab">Section 2</a></li>
				</ul>
				<div class="tab-content tab-content-bordered">
					<div class="tab-pane" id="bs-tabdrop-tab1">
						<div class="table-primary">
							<table cellpadding="0" cellspacing="0" border="0"
								class="table table-striped table-bordered" id="datatables-users">
								<thead>
									<tr>
										<th>Name</th>
										<th>Instituition</th>
										<th class="hidden-xs hidden-sm">Register Date</th>
										<th style="width: 150px; min-width: 150px">Problems Solveds</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>name</td>
										<td>institution</td>
										<td>date</td>
										<td>solved</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane" id="bs-tabdrop-tab2">
						<p>Howdy, I'm in Section 2.</p>
					</div>
				</div>

			</div>
		</div>

	</div>
</div>