<div class="page-header">
	<h1>Contests</h1>
</div>

<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">My Contests</span>
			</div>
			<div class="panel-body">
				<div class="table-primary">
					<table cellpadding="0" cellspacing="0" border="0"
						class="table table-striped table-bordered"
						id="datatables-problems">
						<thead>
							<tr>
								<th style="width: 80px; min-width: 80px;">Number</th>
								<th>Title</th>
								<th>Description</th>
								<th style="width: 80px; min-width: 80px;">Begin</th>
								<th style="width: 80px; min-width: 80px;">End</th>
							</tr>
						</thead>
						<tbody>
							
						<?php foreach($this->contests as $contest){ ?>
							<tr class="odd gradeX"
								>
								<td><?php echo $contest['id']; ?></td>
								<td><a href="index.php/contest/#"><?php echo $contest['title']; ?></a></td>
								<td><a href="index.php/contest/#"><?php echo $contest['description']; ?></a></td>
								<td><?php echo $contest['begin']; ?></td> 
								<td><?php echo $contest['end']; ?></td>
							</tr>
						<?php }?>
						
						
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>