<div class="page-header">
	<h1>User Register</h1>
</div>

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {		
						
						jQuery.validator.addMethod("alphanumeric", function(value, element) {
							return this.optional(element) || /^\w+$/i.test(value);
						}, "Letters, numbers, and underscores only please");
						
						$("#jq-validation-form").validate({
							ignore: '.ignore, .select2-input',
							focusInvalid: false,
							rules: {
								'title': {
									required: true
								},
								'begin': {
									required: true
								},
								'end': {
									required: true
								},
								'jq-validation-policy': {
									required: true
								},
							},
							messages: {
								'jq-validation-policy': 'You must check it!'
							}
						});
					});
				</script>
		<!-- / Javascript -->

		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">Informations</span>
			</div>
			<div class="panel-body">

				<?php if($this->error) echo "<div class='note note-danger'>$this->error</div>"; ?>			

				<form class="form-horizontal" id="jq-validation-form" method="post">
					<div class="form-group">
						<label for="title" class="col-sm-3 control-label">Title</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="title" name="title"
								placeholder="Title" value="<?php echo $_POST["title"]; ?>">
						</div>
					</div>			

					<div class="form-group">
						<label for="begin" class="col-sm-3 control-label">Begin</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="begin" name="begin"
								placeholder="Begin" value="<?php echo $_POST["begin"]; ?>">
						</div>
					</div>	
					
					<div class="form-group">
						<label for="end" class="col-sm-3 control-label">End</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="end" name="end"
								placeholder="End" value="<?php echo $_POST["end"]; ?>">
						</div>
					</div>		
					
					<hr class="panel-wide">

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<div class="checkbox">
								<label> <input type="checkbox" name="jq-validation-policy"
									id="jq-validation-policy" class="px"> <span class="lbl">Confirm
										policy</span>
								</label>
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<button type="submit" class="btn btn-primary">Sign in</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- /5. $JQUERY_VALIDATION -->