<style>
#datatables-problems tr:hover td {
	background-color: #eee !important;
	cursor: pointer;
}
</style>

<div class="page-header">
	<h1>Problems</h1>
	<?php if(Application_Model_Auth::isAdmin()){ ?>
	<div class="btn-group btn-group pull-right">
		<a class="btn btn-primary" href="index.php/problem/register">New Problem</a>
		<a class="btn btn-primary" href="index.php/tag/list">Tags</a>
	</div>
	<?php } ?>
</div>

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {
						$('#datatables-problems').dataTable();
						$('#datatables-problems_wrapper .table-caption').text('<?php echo $this->title;?>');
						$('#datatables-problems_wrapper .dataTables_filter input').attr('placeholder', 'Search...');
					});
				</script>

		<div class="panel">
			<div class="panel-body">
				<div class="table-primary">
					<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="datatables-problems">
						<thead>
							<tr>
								<th style="width: 100px; min-width: 100px;">Number</th>
								<th>Title</th>
								<th>From</th>
								<th style="width: 200px">Solutions / Total Submissions</th>
								<th style="width: 200px">Solved / Total Users</th>
								<th style="width: 120px; min-width: 120px;">Date Register</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach($this->problems as $problem){ ?>
							<tr class="odd gradeX" onclick="document.location='index.php/p/<?php echo $problem['id']; ?>'">
								<td><?php echo $problem['id']; ?></td>
								<td><?php echo $problem['title']; ?></td>
								<td><?php echo $problem['from']; ?></td>
								<?php 
									$total = $problem['ac']+$problem['pe']+$problem['wa']+$problem['ce']+$problem['re']+$problem['tl'];
									$ratio = $total?number_format($problem['ac']/$total*100, 2):0;
									$label = $total?($ratio<10?"0":"").$ratio."% ($problem[ac]/$total)":"0/0";
									if($ratio <= 20) $class = "progress-bar-danger";
									else if($ratio <= 40) $class = "progress-bar-warning";
									else if($ratio <= 60) $class = "";
									else if($ratio <= 80) $class = "progress-bar-info";
									else $class = "progress-bar-success";
								?>
								<td><?php echo $label;?><div class="progress no-margin" style="height: 6px;"><div class="progress-bar <?php echo $class;?>" style="width: <?php echo $ratio;?>%;"></div></div></td>
								<?php 
									$total = $problem['tried']+$problem['solved'];
									$ratio = $total?number_format($problem['solved']/$total*100, 2):0;
									$label = $total?($ratio<10?"0":"").$ratio."% ($problem[solved]/$total)":"0/0";
									if($ratio <= 20) $class = "progress-bar-danger";
									else if($ratio <= 40) $class = "progress-bar-warning";
									else if($ratio <= 60) $class = "";
									else if($ratio <= 80) $class = "progress-bar-info";
									else $class = "progress-bar-success";
								?>
								<td><?php echo $label;?><div class="progress no-margin" style="height: 6px;"><div class="progress-bar <?php echo $class;?>" style="width: <?php echo $ratio;?>%;"></div></div></td>
								<td><?php echo substr($problem['date'], 0, 10); ?></td>
							</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>


