<div class="page-header">
	<h1>Problem Register</h1>
</div>
<!-- / .page-header -->



<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {
					
						// Multiselect
						$("#users").select2({
							placeholder: "Select a User"
						});

						// Setup validation
						$("#jq-validation-form").validate({
							ignore: '.ignore, .select2-input',
							focusInvalid: false,
							rules: {
								'author': {
									required: true
								},
								'title': {
									required: true
								},
								'timelimit':{ 
									required: true,
								},	
								'description': {
									  required: true,
									  
								},							
							},
							errorPlacement: function(error, element) {
								error.addClass("help-block");
								if (element.attr("name") == "description") error.insertAfter(element.parent());
								else error.insertAfter(element);
							}
						});
					});
				</script>
		<!-- / Javascript -->

		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">Informations</span>
			</div>
			<div class="panel-body">

				<form class="form-horizontal" id="jq-validation-form" method="post" enctype="multipart/form-data">
					<div class="form-group">
						<label for="author" class="col-sm-3 control-label">Author</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="author" name="author"
								placeholder="Author">
						</div>
					</div>

					
					<div class="form-group">
						<label for="title" class="col-sm-3 control-label">Title</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="title" name="title"
								placeholder="Title">
						</div>
					</div>


					<div class="form-group">
						<label for="timelimit" class="col-sm-3 control-label">Time Limit</label>
						<div class="col-sm-3">
							<input type="text" class="form-control" id="timelimit" name="timelimit"
								placeholder="Time Limit">
						</div>
					</div>
					
					<div class="form-group">
						<label for="hide" class="col-sm-3 control-label">Hide</label>
						<div class="col-sm-1">
							<input type="checkbox" class="form-control" id="hide" name="hide"
								placeholder="Hide">
						</div>
					</div>

					<div class="form-group">
						<label for="description" class="col-sm-3 control-label">File Description</label>
						<script>
							init.push(function () {
								$('#finputs').pixelFileInput({ placeholder: 'No file selected...' });
							})
						</script>

						<div class="col-sm-7">
							<input type="file" id="description" name="description">
						</div>
					</div>

					<hr class="panel-wide">

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<button type="submit" class="btn btn-primary">Confirm</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- /5. $JQUERY_VALIDATION -->