<div class="page-header">
	<h1>Problem Register</h1>
</div>
<!-- / .page-header -->



<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {
					
		

						// Setup validation
						$("#jq-validation-form").validate({
							ignore: '.ignore, .select2-input',
							focusInvalid: false,
							rules: {
								'number': {
									required: true
								},
								'name': {
									required: true
								},
								'description': {
								  required: true,
								},		
								'finputs': {
									  required: true,
									  
								},							
							},
							errorPlacement: function(error, element) {
								error.addClass("help-block");
								if (element.attr("name") == "finputs") error.insertAfter(element.parent());
								else error.insertAfter(element);
							}
						});
					});
				</script>
		<!-- / Javascript -->

		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">Informations</span>
			</div>
			<div class="panel-body">
				<div class="note note-danger">This email is already registered.</div>

				<form class="form-horizontal" id="jq-validation-form" method="post">
					<div class="form-group">
						<label for="number" class="col-sm-3 control-label">Number</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="number" name="number"
								placeholder="Number">
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-sm-3 control-label">Name</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="name" name="name"
								placeholder="Name">
						</div>
					</div>


					<div class="form-group">
						<label for="description" class="col-sm-3 control-label">Description</label>
						<div class="col-sm-7">
							<textarea class="form-control" rows="30" id="description"
								name="description" placeholder="Description"></textarea>
						</div>
					</div>

					<div class="form-group">
						<label for="description" class="col-sm-3 control-label">File</label>
						<script>
							init.push(function () {
								$('#finputs').pixelFileInput({ placeholder: 'No file selected...' });
							})
						</script>					
						
						<div class="col-sm-7">
							<input type="file" id="finputs" name="finputs">
						</div>
					</div>

					<hr class="panel-wide">

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<button type="submit" class="btn btn-primary">Confirm</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- /5. $JQUERY_VALIDATION -->