<!DOCTYPE html>
<!--[if IE 8]>         <html class="ie8"> <![endif]-->
<!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
<!--[if gt IE 9]><!-->
<html class="gt-ie8 gt-ie9 not-ie">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>UFFS Online Judge</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

<base href="/xp/public/">

<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin' rel='stylesheet' type='text/css'>
<link href="assets/stylesheets/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="assets/stylesheets/pixel-admin.min.css" rel="stylesheet" type="text/css">
<link href="assets/stylesheets/widgets.min.css" rel="stylesheet" type="text/css">
<link href="assets/stylesheets/rtl.min.css" rel="stylesheet" type="text/css">
<link href="assets/stylesheets/themes.min.css" rel="stylesheet" type="text/css">

<!--[if lt IE 9]>
		<script src="assets/javascripts/ie.min.js"></script>
	<![endif]-->


<script>var init = [];</script>
<style>
.avatar {
	width: 80px;
	border-radius: 40px;
	margin-right: 10px;
}

.avatar-sm {
	width: 40px;
	border-radius: 20px;
	margin-right: 10px;
}

.avatar-xm {
	width: 30px;
	border-radius: 15px;
	margin-right: 10px;
}
</style>
</head>

<body class="theme-default main-menu-animated">
	<div id="main-wrapper">
		<div id="main-navbar" class="navbar navbar-inverse" role="navigation">
			<!-- Main menu toggle -->
			<button type="button" id="main-menu-toggle">
				<i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span>
			</button>

			<div class="navbar-inner">
				<!-- Main navbar header -->
				<div class="navbar-header">

					<!-- Logo -->
					<a href="index.html" class="navbar-brand">
						<div>
							<img alt="Pixel Admin" src="assets/images/pixel-admin/main-navbar-logo.png">
						</div> <span class="text-semibold">UFFS</span> <span class="text-slim">Online Judge</span>
					</a>

					<!-- Main navbar toggle -->
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse">
						<i class="navbar-icon fa fa-bars"></i>
					</button>

				</div>
				<!-- / .navbar-header -->

				<div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
					<div>
						<ul class="nav navbar-nav">
							<li><a href="index.php/index/index">Home</a></li>
							<li><a href="index.php/problem/list">Problems</a></li>
							<li><a href="#">UFFS</a></li>
							<li><a href="#">Sobre</a></li>
						</ul>
						<!-- / .navbar-nav -->

						<div class="right clearfix">
							<ul class="nav navbar-nav pull-right right-navbar-nav">
								<li>
									<form action="index.php/problem/list" method="post" class="navbar-form pull-left">
										<input type="text" class="form-control" placeholder="Search Problems" name="search">
									</form>
								</li>

								<li class="dropdown"><a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown"> <img src="http://www.gravatar.com/avatar/<?php echo md5($this->user[email])?>?d=mm&s=280" alt=""> <span>
								<?php
								if (Application_Model_Auth::getUser ()) {
									$user = Application_Model_Auth::getUser ();
									echo $user ['name'];
								} else {
									echo 'Guest';
								}
								?></span>
								</a>
									<ul class="dropdown-menu">
										<li><a href="index.php/user/edit"><i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Edit</a></li>
										<li class="divider"></li>
										<li><a href="index.php/index/logout"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Logout</a></li>
									</ul></li>
							</ul>
							<!-- / .navbar-nav -->
						</div>
						<!-- / .right -->
					</div>
				</div>
				<!-- / #main-navbar-collapse -->
			</div>
			<!-- / .navbar-inner -->
		</div>
		<!-- / #main-navbar -->
		<!-- /2. $END_MAIN_NAVIGATION -->


		<!-- 4. $MAIN_MENU =================================================================================

-->
		<div id="main-menu" role="navigation">
			<div id="main-menu-inner">
				<div class="menu-content top" id="menu-content-demo">
					<!-- Menu custom content demo
					 CSS:        styles/pixel-admin-less/demo.less or styles/pixel-admin-scss/_demo.scss
					 Javascript: html/assets/demo/demo.js
				 -->
					<div>
						<div class="text-bg">
							<span class="text-semibold"><?php
							if (Application_Model_Auth::getUser ()) {
								$user = Application_Model_Auth::getUser ();
								echo $user['name'];
							} else {
								echo 'Visitant';
							}
							?></span>
						</div>

						<img src="http://www.gravatar.com/avatar/<?php echo md5($user['email'])?>?d=mm&s=280" alt="" class="">
						<div class="btn-group">
							<a href="#" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-envelope"></i></a> 
							<a href="#" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-user"></i></a> 
							<a href="#" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-cog"></i></a> 
							<a href="index.php/index/logout" class="btn btn-xs btn-danger btn-outline dark"><i class="fa fa-power-off"></i></a>
						</div>
						<a href="#" class="close">&times;</a>
					</div>
				</div>
				
				<?php 
					function active($controller = null, $action = null, $param = null, $open = false){
						if($controller && $controller != Zend_Controller_Front::getInstance()->getRequest()->getControllerName()) return;
						if($action && $action != Zend_Controller_Front::getInstance()->getRequest()->getActionName()) return;
						if($param && !Zend_Controller_Front::getInstance()->getRequest()->getParam($param)) return;
						echo "active";
						if($open) echo " open";
					}
				?>
				
				
				<ul class="navigation">
					<?php if($user) {?>
					<li class="<?php active('user', 'index'); ?>"><a href="index.php/user"> <i class="menu-icon fa fa-user"></i><span class="mm-text">My Account</span></a></li>
					<?php }?>
					<?php if(!$user) {?>
						<li class="<?php active('user', 'register'); ?>" ><a href="index.php/user/register"><i class="menu-icon fa fa-user"></i><span class="mm-text">Sign Up</span></a></li>
					<?php }?>
					<li class="<?php active('user', 'list'); ?>"><a href="index.php/user/list"><i class="menu-icon fa fa-group"></i><span class="mm-text">Users</span></a></li>
					<li class="<?php active('submission', 'rank'); ?>"><a href="index.php/submission/rank"><i class="menu-icon fa fa-trophy"></i><span class="mm-text">Ranking</span></a></li>
					<li class="<?php active('submission', 'index'); ?>"><a href="index.php/submission"><i class="menu-icon fa fa-lightbulb-o"></i><span class="mm-text">Quick Submit</span></a></li>
					<li class="mm-dropdown <?php active('submission', 'user', null, true); active('submission', 'list', null, true); ?>"><a href="index.php"><i class="menu-icon fa fa-check-square-o"></i><span class="mm-text">Submissions</span></a>
						<ul>
							<li class="<?php active('submission', 'user'); ?>"><a tabindex="-1" href="index.php/submission/user/1"><span class="mm-text">My Submission <span class="label label-success"></span></span></a></li>
							<li class="<?php active('submission', 'list'); ?>"><a tabindex="-1" href="index.php/submission/list"><span class="mm-text">Recent Submissions <span class="label label-success"></span></span></a></li>
						</ul></li>

					<li class="mm-dropdown"><a href="index.php"><i class="menu-icon fa fa-outdent"></i><span class="mm-text">Contests</span></a>
						<ul>
							<li><a tabindex="-1" href="index.php/contest/list"><span class="mm-text">All Contests <span class="label label-success"></span></span></a></li>
							<li><a tabindex="-1" href="index.php/contest/enroled"><span class="mm-text">Enroled Contests <span class="label label-success"></span></span></a></li>
							<li><a tabindex="-1" href="index.php/contest/my"><span class="mm-text">My Contests <span class="label label-success"></span></span></a></li>
							<li><a tabindex="-1" href="index.php/contest/register"><span class="mm-text">Create Contest <span class="label label-success"></span></span></a></li>
						</ul></li>

					<li class="mm-dropdown <?php active('problem', null, null, true); ?>"><a href="index.php/problem/list"><i class="menu-icon fa fa-flask"></i><span class="mm-text">Problems</span><span class="label label-success"></span></a>
						<ul>
							<?php 
								$tagAtual = Zend_Controller_Front::getInstance()->getRequest()->getParam("tag");
							?>
							<li class="<?php if(!$tagAtual) active('problem', 'list'); ?>"><a tabindex="-1" href="index.php/problem/list/"><span class="mm-text">All Problems<span class="label label-success"></span></span></a></li>
							<?php foreach(Application_Model_TagManager::getAll(null,"name") as $tag){?>
								<li class="<?php if($tagAtual == $tag['id']) active('problem', 'list'); ?>"><a tabindex="-1" href="index.php/problem/list/tag/<?php echo $tag['id'];?>"><span class="mm-text"><?php echo $tag['name'];?><span class="label label-success"></span></span></a></li>
							<?php }?>
						</ul></li>
				</ul>
			</div>
		</div>
		
		<div id="content-wrapper">
		<?php echo $this->layout()->content?>
	</div>

		<div id="main-menu-bg"></div>
	</div>
	<!--[if !IE]> -->
	<script type="text/javascript"> window.jQuery || document.write("<script src='https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js'>"+"<"+"/script>"); </script>
	<!-- <![endif]-->
	<!--[if lte IE 9]>
		<script type="text/javascript"> window.jQuery || document.write("<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'>"+"<"+"/script>"); </script>
	<![endif]-->


	<script src="assets/javascripts/bootstrap.min.js"></script>
	<script src="assets/javascripts/pixel-admin.min.js"></script>

	<script type="text/javascript">
	init.push(function () {
		// Javascript code here
	})
	window.PixelAdmin.start(init);
</script>

</body>
</html>