<div class="page-header">
	<h1>User</h1>
</div>

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {		
						
						$("#jq-validation-form").validate({
							ignore: '.ignore, .select2-input',
							focusInvalid: false,
							rules: {
								'email': {
								  required: true,
								  email: true
								},
								'name': {
									required: true
								},
								'institution': {
									maxlength: 10
								},
								'page': {
									url: true
								},
								'password': {
									minlength: 6,
									maxlength: 20
								},
								'password-confirmation': {
									minlength: 6,
									equalTo: "#password"
								},
								<?php if(!Application_Model_Auth::isAdmin()){ ?>
								'current-password': {
									minlength: 6,
									maxlength: 20,
									required: true
								},
								<?php } ?>
								
							}
						});
					});
				</script>

		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">Edit Profile</span>
			</div>
			<div class="panel-body">

				<?php if($this->error) echo "<div class='note note-danger'>$this->error</div>"; ?>	
				<?php if($this->success) { ?>			

					<div id="success" class="modal modal-alert modal-success fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<i class="fa fa-check-circle"></i>
								</div>
								<div class="modal-title"><?php echo $this->success;?></div>
								<div class="modal-footer">
									<button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
								</div>
							</div> <!-- / .modal-content -->
						</div> <!-- / .modal-dialog -->
					</div>
					<script>init.push(function(){ $('#success').modal();});</script>
				<?php } ?>
				
				<form class="form-horizontal" id="jq-validation-form" method="post">
					<div class="form-group">
						<label for="name" class="col-sm-3 control-label">Name</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="name" name="name"
								placeholder="Name" value="<?php echo $_POST["name"]; ?>">
						</div>
					</div>
				
					<div class="form-group">
						<label for="email" class="col-sm-3 control-label">Email</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="email"
								name="email" placeholder="Email" value="<?php echo $_POST["email"]; ?>">
						</div>
					</div>

					<div class="form-group">
						<label for="institution" class="col-sm-3 control-label">Institution</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="institution"
								name="institution" placeholder="Institution" value="<?php echo $_POST["institution"]; ?>">
						</div>
					</div>
					
					<div class="form-group">
						<label for="page" class="col-sm-3 control-label">Page</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="page"
								name="page" placeholder="Page" value="<?php echo $_POST["page"]; ?>">
							<p class="help-block">Example http://twitter.com/mytwitter</p>
						</div>
					</div>
					
					
					<div class="form-group">
						<label for="password" class="col-sm-3 control-label">New Password</label>
						<div class="col-sm-7">
				<input type="password" class="form-control" id="password"
								name="password" placeholder="Not changed">

						</div>
					</div>

					<div class="form-group">
						<label for="password-confirmation" class="col-sm-3 control-label">Confirm
							new password</label>
						<div class="col-sm-7">
							<input type="password" class="form-control"
								id="password-confirmation" name="password-confirmation" placeholder="Confirm new password">
						</div>
					</div>

					<?php if(!Application_Model_Auth::isAdmin()){ ?>
					<div class="form-group">
						<label for="current-password" class="col-sm-3 control-label">Current Password</label>
						<div class="col-sm-7">
				<input type="password" class="form-control" id="current-password"
								name="current-password" placeholder="Current Password">

						</div>
					</div>
					<?php } ?>

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<button type="submit" class="btn btn-primary">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- /5. $JQUERY_VALIDATION -->