<div class="page-header">
	<h1>Users</h1>
</div>

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {
						$('#jq-datatables-example').dataTable();
						$('#jq-datatables-example_wrapper .table-caption').text('Llist All Users');
						$('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Search...');
					});
				</script>

		<div class="panel">
			<div class="panel-body">
				<div class="table-primary">
					<table cellpadding="0" cellspacing="0" border="0"
						class="table table-striped table-bordered"
						id="jq-datatables-example">
						<thead>
							<tr>
								<th>Name</th>
								<th>Instituition</th>
								<th>Register Date</th>
								<th style="width: 300px;">Problems Solveds</th>
								<?php if(Application_Model_Auth::isAdmin()) { ?>
								<th style="width: 150px;">Action</th>
								<?php } ?>
							</tr>
						</thead>
						<tbody>
						<?php foreach($this->users as $user){ ?>
							<tr class="odd gradeX">
								<td><?php echo $user['name']; ?></td>
								<td><?php echo $user['institution']; ?></td>
								<td><?php echo substr($user['date'], 0, 10); ?></td>
								<td class="center"><?php echo $user['solved']; ?></td>
								<?php if(Application_Model_Auth::isAdmin()) { ?>
								<td>
									<div class="btn-group">
										<button type="button" class="btn btn-primary">View</button>										
										<button type="button" class="btn btn-primary dropdown-toggle"
											data-toggle="dropdown">
											<i class="fa fa-caret-down"></i>
										</button>
										<ul class="dropdown-menu">
											<li><a href="#">Edit</a></li>
											<li><a href="#">Remove</a></li>
										</ul>
									</div>
								</td>
								<?php } ?>
							</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>


