
<div class="page-header">
	<h1>User Profile</h1>
	
	<?php 
		$login = Application_Model_Auth::getUser();
		if($login['id'] == $this->user['id'] || Application_Model_Auth::isAdmin()){
	?>
	<div class="btn-group btn-group pull-right">
		<a class="btn btn-primary" href="index.php/user/edit/id/<?php echo $this->user['id'];?>">Edit Profile</a>
		<a class="btn btn-primary" href="https://en.gravatar.com/connect/" target="_blank">Change Image</a>
		
		<?php if(Application_Model_Auth::isAdmin()){ ?>
		
		<button class="btn btn-primary" id="remove">Remove</button>
		<script>
		init.push(function () {
			$('#remove').on('click', function () {
				bootbox.confirm({
					message: "Are you sure?",
					callback: function(result) {
						if(result) document.location = "index.php/user/remove/id/<?php echo $this->user['id'];?>";
					},
					className: "bootbox-sm"
				});
			});
		});
		</script>
		<?php } ?>
	</div>
	<?php } ?>
</div>

<script>

init.push(function () {

	var totalTried = <?php echo $this->user['tried']; ?>;
	var totalSubmissions = <?php echo $this->submissions; ?>;
	
	if(totalSubmissions) Morris.Donut({
		element: 'submissions',
		data: [
			{ label: 'AC', value: <?php echo $this->user['ac']; ?> },
			{ label: 'PE', value: <?php echo $this->user['pe']; ?> },
			{ label: 'WA', value: <?php echo $this->user['wa']; ?> },
			{ label: 'CE', value: <?php echo $this->user['ce']; ?> },
			{ label: 'RE', value: <?php echo $this->user['re']; ?> },
			{ label: 'TL', value: <?php echo $this->user['tl']; ?> }
		],
		colors: PixelAdmin.settings.consts.COLORS,
		resize: true,
		labelColor: '#888',
		formatter: function (y) { 
			return y + " ("+(y/totalSubmissions*100).toFixed(2)+"%)"; 
		}
	});

	
	if(totalTried) Morris.Donut({
		element: 'tried',
		data: [
			{ label: 'Solved', value: <?php echo $this->user['solved']; ?> },
			{ label: 'Unsolved', value: <?php echo $this->user['tried']-$this->user['solved']; ?> }
		],
		colors: PixelAdmin.settings.consts.COLORS,
		resize: true,
		labelColor: '#888',
		formatter: function (y) { 
			return y + " ("+(y/totalTried*100).toFixed(2)+"%)"; 
		}
	});
});
</script>

<div class="panel">
	<div class="panel-body">

		<div class="row">
			<div class="col-md-4">

				<div
					class="panel panel-primary panel-dark panel-body-colorful widget-profile widget-profile-centered no-margin">
					<div class="panel-heading" style="height: 263px;">
						<img
							src="http://www.gravatar.com/avatar/<?php echo md5($this->user[email])?>?d=mm&s=280"
							alt="" class="widget-profile-avatar"
							style="width: 140px; height: 140px;">
						<div class="widget-profile-header">
					<?php
					echo "<span>{$this->user[name]}</span>";
					if ($this->user ['page'])
						echo "<br><a href='{$this->user[page]}'>{$this->user[page]}</a>";
					if ($this->user ['institution'])
						echo "<br>{$this->user[institution]}";
					?>
				</div>
					</div>
				</div>

			</div>

			<div class="col-md-4">
				<div class="panel panel-primary panel-dark no-margin"
					style="height: 265px;">
					<div class="panel-heading">
						<span class="table-caption text-semibold"><?php echo $this->submissions; ?> Submissions</span>
					</div>
					<div class="panel-body">
						<div class="graph-container text-center">
							<?php if($this->submissions) { ?>
								<div id="submissions" style="height: 180px;" class="graph"></div>
							<?php }else{ ?>
								<i style="font-size: 120px; color: #EEE; margin-top: 30px"
								class="fa fa-bar-chart-o"></i>
							<?php }?>
						</div>
						<div class="col-md-4"></div>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="panel panel-primary panel-dark no-margin"
					style="height: 265px;">
					<div class="panel-heading">
						<span class="table-caption text-semibold"><?php echo $this->user['tried']; ?> Problems Tried</span>
					</div>
					<div class="panel-body">
						<div class="graph-container text-center">
							<?php if($this->user['tried']) { ?>
								<div id="tried" style="height: 180px;" class="graph"></div>
							<?php }else{ ?>
								<i style="font-size: 120px; color: #EEE; margin-top: 30px"
								class="fa fa-bar-chart-o"></i>
							<?php }?>
						</div>
						<div class="col-md-4"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {
						$('#datatables-problems').dataTable();
						$('#datatables-problems_wrapper .table-caption').text('Problems solved');
						$('#datatables-problems_wrapper .dataTables_filter input').attr('placeholder', 'Search...');
					});
				</script>

		<div class="panel">
			<div class="panel-body">
				<div class="table-primary">
					<table cellpadding="0" cellspacing="0" border="0"
						class="table table-striped table-bordered"
						id="datatables-problems">
						<thead>
							<tr>
								<th style="width: 100px; min-width: 100px;">Submission</th>
								<th>Problem</th>
								<th style="width: 150px; min-width: 150px;">Date</th>
								<th style="width: 80px; min-width: 80px;">Time</th>
								<th style="width: 90px; min-width: 9px;">Language</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach($this->problems as $value){ ?>
							<tr class="odd gradeX"
								onclick="document.location='index.php/p/<?php echo $value['id']; ?>'">
								<td><?php echo $value['idSub'];?></td>
								<td><?php echo $value['id']." - ".$value['title'];?>
								<td><?php echo $value['date']; ?></td>
								<td><?php echo $value['time']; ?> ms</td>
								<td><?php echo $value['language']; ?></td>
							</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>