<style>
#datatables-users tr:hover td {
	background-color: #eee !important;
	cursor: pointer;
}
</style>

<div class="page-header">
	<h1>Users</h1>
</div>

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {
						$('#datatables-users').dataTable();
						$('#datatables-users_wrapper .table-caption').text('List All Users');
						$('#datatables-users_wrapper .dataTables_filter input').attr('placeholder', 'Search...');
					});
				</script>

		<div class="panel">
			<div class="panel-body">
				<div class="table-primary">
					<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="datatables-users">
						<thead>
							<tr>
								<th>Name</th>
								<th>Instituition</th>
								<th>Register Date</th>
								<th style="width: 150px; min-width: 150px">Problems Solveds</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach($this->users as $user){ ?>
							<tr class="odd gradeX" onclick="document.location='index.php/u/<?php echo $user['login']; ?>'">
								<td><?php echo $user['name']; ?></td>
								<td><?php echo $user['institution']; ?></td>
								<td><?php echo substr($user['date'], 0, 10); ?></td>
								<td class="text-center"><?php echo $user['solved']; ?></td>
							</tr>
						<?php }?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>


