<div class="page-header">
	<h1>User Statistics</h1>
</div>

<script>
init.push(function () {
	Morris.Donut({
		element: 'submissions',
		data: [
			{ label: 'Jam', value: 25 },
			{ label: 'Frosted', value: 40 },
			{ label: 'Custard', value: 25 },
			{ label: 'Sugar', value: 10 },
			{ label: 'Frosted', value: 40 },
			{ label: 'Custard', value: 25 },
			{ label: 'Sugar', value: 10 }
		],
		colors: PixelAdmin.settings.consts.COLORS,
		resize: true,
		labelColor: '#888',
		formatter: function (y) { return y + "%" }
	});
});
init.push(function () {
	Morris.Donut({
		element: 'tried',
		data: [
			{ label: 'Solved', value: 25 },
			{ label: 'Unsolved', value: 40 }
		],
		colors: PixelAdmin.settings.consts.COLORS,
		resize: true,
		labelColor: '#888',
		formatter: function (y) { return y + "%" }
	});
});
</script>


<div class="row">
	<div class="col-md-4">

		<div
			class="panel panel-info panel-dark panel-body-colorful widget-profile widget-profile-centered">
			<div class="panel-heading"  style="height:263px;">
				<img src="assets/demo/avatars/1.jpg" alt=""
					class="widget-profile-avatar" style="width: 140px; height: 140px;">
				<div class="widget-profile-header">
					<span>John Doe</span><br><a href="https://twitter.com/test">https://twitter.com/test</a><br>UFFS
				</div>
			</div>
		</div>

	</div>

	<div class="col-md-4">
		<div class="panel panel-info panel-dark">
			<div class="panel-heading"> <span class="panel-title">10 Submissions</span> 
			</div>
			<div class="panel-body">
				<div class="graph-container">
					<div id="submissions" style="height:180px;" class="graph"></div>
				</div>
				<div class="col-md-4"></div>
			</div>
		</div>
	</div>
	
	<div class="col-md-4">
		<div class="panel panel-info panel-dark">
			<div class="panel-heading"> <span class="panel-title">10 Problems Tried</span> </div>
			<div class="panel-body">
				<div class="graph-container">
					<div id="tried" style="height:180px;" class="graph"></div>
				</div>
				<div class="col-md-4"></div>
			</div>
		</div>
	</div>
</div>