<div class="page-header">
	<h1>
		User Register
	</h1>
</div>
<!-- / .page-header -->

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {
					
		

						// Setup validation
						$("#jq-validation-form").validate({
							ignore: '.ignore, .select2-input',
							focusInvalid: false,
							rules: {
								'email': {
								  required: true,
								  email: true
								},
								
								'password': {
									required: true,
									minlength: 6,
									maxlength: 20
								},
								'password-confirmation': {
									required: true,
									minlength: 6,
									equalTo: "#password"
								},
								'name': {
									required: true
								},
								'nickname': {
									required: true
								},
								'instituition': {
									maxlength: 6
								},
								'jq-validation-policy': {
									required: true
								}
							},
							messages: {
								'jq-validation-policy': 'You must check it!'
							}
						});
					});
				</script>
		<!-- / Javascript -->

		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">Informations</span>
			</div>
			<div class="panel-body">
				<div class="note note-danger"> 
					This email is already registered.
				</div>

				<form class="form-horizontal" id="jq-validation-form" method="post">
					<div class="form-group">
						<label for="name" class="col-sm-3 control-label">Name</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="name" name="name"
								placeholder="Name">
						</div>
					</div>
				
				
					<div class="form-group">
						<label for="email" class="col-sm-3 control-label">Email</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="email"
								name="email" placeholder="Email">
						</div>
					</div>

					<div class="form-group">
						<label for="nickname" class="col-sm-3 control-label">Nickname</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="nickname" name="nickname"
								placeholder="Nickname">
						</div>
					</div>

					<div class="form-group">
						<label for="password" class="col-sm-3 control-label">Password</label>
						<div class="col-sm-7">
							<input type="password" class="form-control"
								id="password" name="password"
								placeholder="Password">
							<p class="help-block">Example block-level help text here.</p>
						</div>
					</div>

					<div class="form-group">
						<label for="password-confirmation"
							class="col-sm-3 control-label">Confirm password</label>
						<div class="col-sm-7">
							<input type="password" class="form-control"
								id="password-confirmation"
								name="password-confirmation"
								placeholder="Confirm password">
							<p class="help-block">Example block-level help text here.</p>
						</div>
					</div>

					<div class="form-group">
						<label for="instituition" class="col-sm-3 control-label">Instituition</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="instituition"
								name="instituition" placeholder="Instituition">
						</div>
					</div>

					

					<hr class="panel-wide">

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<div class="checkbox">
								<label> <input type="checkbox" name="jq-validation-policy"
									id="jq-validation-policy" class="px"> <span class="lbl">Confirm
										policy</span>
								</label>
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<button type="submit" class="btn btn-primary">Sign in</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- /5. $JQUERY_VALIDATION -->