<div class="page-header">
	<h1>User Register</h1>
</div>

<div class="row">
	<div class="col-sm-12">
		<script>
					init.push(function () {		
						
						jQuery.validator.addMethod("alphanumeric", function(value, element) {
							return this.optional(element) || /^\w+$/i.test(value);
						}, "Letters, numbers, and underscores only please");
						
						$("#jq-validation-form").validate({
							ignore: '.ignore, .select2-input',
							focusInvalid: false,
							rules: {
								'email': {
								  required: true,
								  email: true
								},
								'login': {
								  required: true,
								  alphanumeric: true,
								  maxlength: 32
								},
								'password': {
									required: true,
									minlength: 6,
									maxlength: 20
								},
								'password-confirmation': {
									required: true,
									minlength: 6,
									equalTo: "#password"
								},
								'name': {
									required: true
								},
								'nickname': {
									required: true
								},
								'institution': {
									maxlength: 6
								},
								'jq-validation-policy': {
									required: true
								},
								'page': {
									url: true
								},
								
							},
							messages: {
								'jq-validation-policy': 'You must check it!'
							}
						});
					});
				</script>
		<!-- / Javascript -->

		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">Informations</span>
			</div>
			<div class="panel-body">

				<?php if($this->error) echo "<div class='note note-danger'>$this->error</div>"; ?>			

				<form class="form-horizontal" id="jq-validation-form" method="post">
					<div class="form-group">
						<label for="name" class="col-sm-3 control-label">Name</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="name" name="name"
								placeholder="Name" value="<?php echo $_POST["name"]; ?>">
						</div>
					</div>			
				
					<div class="form-group">
						<label for="login" class="col-sm-3 control-label">Login</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="login" name="login"
								placeholder="Login" value="<?php echo $_POST["login"]; ?>">
						</div>
					</div>
				
					<div class="form-group">
						<label for="email" class="col-sm-3 control-label">Email</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="email"
								name="email" placeholder="Email" value="<?php echo $_POST["email"]; ?>">
						</div>
					</div>

					<div class="form-group">
						<label for="nickname" class="col-sm-3 control-label">Nickname</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="nickname" name="nickname"
								placeholder="Nickname" value="<?php echo $_POST["nickname"]; ?>">
						</div>
					</div>

					<div class="form-group">
						<label for="password" class="col-sm-3 control-label">Password</label>
						<div class="col-sm-7">
				<input type="password" class="form-control" id="password"
								name="password" placeholder="Password">

						</div>
					</div>

					<div class="form-group">
						<label for="password-confirmation" class="col-sm-3 control-label">Confirm
							password</label>
						<div class="col-sm-7">
							<input type="password" class="form-control"
								id="password-confirmation" name="password-confirmation"
								placeholder="Confirm password">
						</div>
					</div>

					<div class="form-group">
						<label for="institution" class="col-sm-3 control-label">Institution</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="institution"
								name="institution" placeholder="Institution" value="<?php echo $_POST["institution"]; ?>">
						</div>
					</div>
					
					<div class="form-group">
						<label for="page" class="col-sm-3 control-label">Page</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="page"
								name="page" placeholder="Page" value="<?php echo $_POST["page"]; ?>">
							<p class="help-block">Example http://twitter.com/mytwitter</p>
						</div>
					</div>

					<hr class="panel-wide">

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<div class="checkbox">
								<label> <input type="checkbox" name="jq-validation-policy"
									id="jq-validation-policy" class="px"> <span class="lbl">Confirm
										policy</span>
								</label>
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-9">
							<button type="submit" class="btn btn-primary">Sign in</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- /5. $JQUERY_VALIDATION -->